name: pokedex_flutter
description: "Pokédex with Flutter and GraphQL"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Estilo iOS y general
  cupertino_icons: ^1.0.8

  # 🔹 GraphQL para consumir la API de PokeAPI
  graphql_flutter: ^5.1.2

  # 🔹 Cache de imágenes para sprites y artes oficiales
  cached_network_image: ^3.3.1

  # 🔹 Navegación moderna (lista ⇄ detalle)
  go_router: ^14.2.0

  # 🔹 Base de datos local para favoritos
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # 🔹 Animaciones suaves (aparición de ítems, transiciones)
  flutter_staggered_animations: ^1.1.1

  # 🔹 Fuente Roboto (ya incluida en Material3)
  google_fonts: ^6.2.1

  # 🔹 Gráficos (Radar Chart para stats)
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  # 🔹 Generador de iconos de la app
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

# --- FLUTTER LAUNCHER ICONS CONFIG ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # required for adaptive icons
# -------------------------------------
